
package Vistas;

import java.awt.Dimension;
import java.awt.Toolkit;
import javax.swing.JOptionPane;


public class Vista_Principal extends javax.swing.JFrame {
    
    public String sesion="";
    public String nombre="";
    
    

    /**
     * Creates new form Vista_Principal
     */
    public Vista_Principal() {
        initComponents();
    }

    public void saludo(){
        this.lbSaludo.setText("Bienvenido "+this.nombre);
    }
    
    public void centrar(){
        Dimension pantalla = Toolkit.getDefaultToolkit().getScreenSize();
        Dimension imagen = pimagen.getSize();
        pimagen.setLocation(((pantalla.width/2)-(imagen.width/2)),((pantalla.height/2)-(imagen.height/2)));
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lbSaludo = new javax.swing.JLabel();
        pimagen = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        menuMantenimiento = new javax.swing.JMenu();
        mmtoCliente = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        mmtoUsuario = new javax.swing.JMenuItem();
        mmtoVehiculo = new javax.swing.JMenuItem();
        menurevision = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));

        lbSaludo.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        lbSaludo.setText("Bienvenido ");

        pimagen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vistas/Fondo.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pimagen)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbSaludo)
                .addContainerGap(749, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbSaludo)
                    .addComponent(pimagen))
                .addContainerGap(308, Short.MAX_VALUE))
        );

        jMenu1.setText("Aplicaciones ");

        menuMantenimiento.setText("Mantenimiento Administrativo");

        mmtoCliente.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_1, java.awt.event.InputEvent.CTRL_MASK));
        mmtoCliente.setText("Clientes");
        mmtoCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mmtoClienteActionPerformed(evt);
            }
        });
        menuMantenimiento.add(mmtoCliente);

        jMenuItem3.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_2, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem3.setText("Empleados");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        menuMantenimiento.add(jMenuItem3);

        jMenuItem4.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_3, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem4.setText("Rutas");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        menuMantenimiento.add(jMenuItem4);

        mmtoUsuario.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_4, java.awt.event.InputEvent.CTRL_MASK));
        mmtoUsuario.setText("Usuarios");
        mmtoUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mmtoUsuarioActionPerformed(evt);
            }
        });
        menuMantenimiento.add(mmtoUsuario);

        mmtoVehiculo.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_5, java.awt.event.InputEvent.CTRL_MASK));
        mmtoVehiculo.setText("Vehiculos");
        mmtoVehiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mmtoVehiculoActionPerformed(evt);
            }
        });
        menuMantenimiento.add(mmtoVehiculo);

        jMenu1.add(menuMantenimiento);

        menurevision.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_R, java.awt.event.InputEvent.CTRL_MASK));
        menurevision.setText("Revision de Rutas");
        menurevision.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menurevisionActionPerformed(evt);
            }
        });
        jMenu1.add(menurevision);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Salir");

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_W, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem1.setText("Cerrar");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem1);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        centrar();
        if (this.nombre.equals("")) {
        lbSaludo.setVisible(false);
        } else{
        saludo();        
        }
        if (sesion.equals("2")) {
            menuMantenimiento.setVisible(false);
            menurevision.setVisible(true);
        }else if (sesion.equals("1")) {
            menuMantenimiento.setVisible(true);
            menurevision.setVisible(false);
        }
    }//GEN-LAST:event_formWindowOpened

    private void mmtoUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mmtoUsuarioActionPerformed
        Mantenimiento_Usuarios mu = new Mantenimiento_Usuarios();
        mu.setLocationRelativeTo(null);
        mu.setVisible(true);
        this.setEnabled(false);
    }//GEN-LAST:event_mmtoUsuarioActionPerformed

    private void mmtoVehiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mmtoVehiculoActionPerformed
        Mantenimiento_Vehiculos mv = new Mantenimiento_Vehiculos();
        mv.setLocationRelativeTo(null);
        mv.setVisible(true);
        this.setEnabled(false);
    }//GEN-LAST:event_mmtoVehiculoActionPerformed

    private void mmtoClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mmtoClienteActionPerformed
        Mantenimiento_Clientes mc = new Mantenimiento_Clientes();
        mc.setLocationRelativeTo(null);
        mc.setVisible(true);
        this.setEnabled(false);
    }//GEN-LAST:event_mmtoClienteActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        Mantenimiento_Empleados me = new Mantenimiento_Empleados();
        me.setLocationRelativeTo(null);
        me.setVisible(true);
        this.setEnabled(false);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        Mantenimiento_Rutas mr = new Mantenimiento_Rutas();
        mr.setLocationRelativeTo(null);
        mr.setVisible(true);
        this.setEnabled(false);
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void menurevisionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menurevisionActionPerformed
        Revision_Rutas rv = new Revision_Rutas();
        rv.setLocationRelativeTo(null);
        rv.setVisible(true);
        this.setEnabled(false);
    }//GEN-LAST:event_menurevisionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Vista_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Vista_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Vista_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Vista_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Vista_Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbSaludo;
    private javax.swing.JMenu menuMantenimiento;
    private javax.swing.JMenuItem menurevision;
    private javax.swing.JMenuItem mmtoCliente;
    private javax.swing.JMenuItem mmtoUsuario;
    private javax.swing.JMenuItem mmtoVehiculo;
    private javax.swing.JLabel pimagen;
    // End of variables declaration//GEN-END:variables
}
